/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonCard: typeof import('./src/components/TreeNode/CommonCard.vue')['default']
    DescriptionTextControl: typeof import('./src/components/DescriptionTextControl/DescriptionTextControl.vue')['default']
    DragH5: typeof import('./src/components/DragH5/DragH5.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    LargeFileUpload: typeof import('./src/components/LargeFileUpload/LargeFileUpload.vue')['default']
    NodeDemo: typeof import('./src/components/TreeNode/NodeDemo.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode/TreeNode.vue')['default']
  }
}
